version: '3.8'


services:
  postgres:
    image: postgres:15
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    networks:
      - chat-network

  chat-app:
    build: .
    container_name: chat-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chat-postgres:5432/chat_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_FLYWAY_URL: jdbc:postgresql://chat-postgres:5432/chat_db
      SPRING_FLYWAY_USER: admin
      SPRING_FLYWAY_PASSWORD: admin
      SPRING_FLYWAY_LOCATIONS: filesystem:/app/db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: "0"
    ports:
      - "8082:8082"
    networks:
      - chat-network
networks:
  chat-network: