------------------------------------------------------------
-- Sekvence
------------------------------------------------------------
CREATE SEQUENCE "SEQ_UCET_ID" MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE "SEQ_POHYB_UCTU_ID" MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE NOORDER;

------------------------------------------------------------
-- UCET (кошелек)
------------------------------------------------------------
CREATE TABLE "UCET" (
    "ID_UCET"         NUMBER(18,0),
    "ID_UZIVATEL"     NUMBER(18,0) NOT NULL,
    "ZUSTATEK"        NUMBER(12,2) DEFAULT 0 NOT NULL,
    "DATUM_VYTVORENI" DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE "UCET" ADD CONSTRAINT "UCET_PK" PRIMARY KEY ("ID_UCET");
ALTER TABLE "UCET" ADD CONSTRAINT "UCET_UZIVATEL_FK" FOREIGN KEY ("ID_UZIVATEL") REFERENCES "UZIVATEL" ("ID_UZIVATEL");
ALTER TABLE "UCET" ADD CONSTRAINT "UCET_UZIVATEL_UQ" UNIQUE ("ID_UZIVATEL");

CREATE OR REPLACE TRIGGER "BI_UCET"
BEFORE INSERT ON "UCET"
FOR EACH ROW
WHEN (NEW."ID_UCET" IS NULL)
BEGIN
  SELECT "SEQ_UCET_ID".NEXTVAL INTO :NEW."ID_UCET" FROM dual;
END;
/

------------------------------------------------------------
-- POHYB_UCTU (движения кошелька)
------------------------------------------------------------
CREATE TABLE "POHYB_UCTU" (
    "ID_POHYB"        NUMBER(18,0),
    "ID_UCET"         NUMBER(18,0) NOT NULL,
    "SMER"            CHAR(1 BYTE) NOT NULL,              -- P=pripsání (credit), D=debet
    "METODA"          VARCHAR2(12 BYTE) NOT NULL,         -- KARTA/HOTOVOST/OBJEDNAVKA/REFUND
    "CASTKA"          NUMBER(12,2) NOT NULL,
    "POZNAMKA"        VARCHAR2(255 BYTE),
    "DATUM_VYTVORENI" DATE DEFAULT SYSDATE NOT NULL,
    "ID_OBJEDNAVKA"   NUMBER(18,0),
    "CISLOKARTY"      VARCHAR2(19 BYTE)
);

ALTER TABLE "POHYB_UCTU" ADD CONSTRAINT "POHYB_UCTU_PK" PRIMARY KEY ("ID_POHYB");
ALTER TABLE "POHYB_UCTU" ADD CONSTRAINT "PU_UCET_FK" FOREIGN KEY ("ID_UCET") REFERENCES "UCET" ("ID_UCET");
ALTER TABLE "POHYB_UCTU" ADD CONSTRAINT "PU_OBJ_FK" FOREIGN KEY ("ID_OBJEDNAVKA") REFERENCES "OBJEDNAVKA" ("ID_OBJEDNAVKA");
ALTER TABLE "POHYB_UCTU" ADD CONSTRAINT "CK_PU_SMER" CHECK ("SMER" IN ('P','D'));
ALTER TABLE "POHYB_UCTU" ADD CONSTRAINT "CK_PU_METODA" CHECK ("METODA" IN ('KARTA','HOTOVOST','OBJEDNAVKA','REFUND'));
ALTER TABLE "POHYB_UCTU" ADD CONSTRAINT "CK_PU_CASTKA_POS" CHECK ("CASTKA" > 0);

CREATE INDEX "PU_UCET_IDX" ON "POHYB_UCTU" ("ID_UCET");
CREATE INDEX "PU_OBJ_IDX"  ON "POHYB_UCTU" ("ID_OBJEDNAVKA");

CREATE OR REPLACE TRIGGER "BI_POHYB_UCTU"
BEFORE INSERT ON "POHYB_UCTU"
FOR EACH ROW
WHEN (NEW."ID_POHYB" IS NULL)
BEGIN
  SELECT "SEQ_POHYB_UCTU_ID".NEXTVAL INTO :NEW."ID_POHYB" FROM dual;
END;
/

------------------------------------------------------------
-- PLATBA: добавить тип U и ссылку на движение кошелька
------------------------------------------------------------
ALTER TABLE "PLATBA" ADD ("ID_POHYB_UCTU" NUMBER(18,0));

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE "PLATBA" DROP CONSTRAINT "CK_PLATBA_TYP"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

ALTER TABLE "PLATBA" ADD CONSTRAINT "CK_PLATBA_TYP" CHECK ("PLATBATYP" IN ('H','K','U'));
ALTER TABLE "PLATBA" ADD CONSTRAINT "PLATBA_PU_FK" FOREIGN KEY ("ID_POHYB_UCTU") REFERENCES "POHYB_UCTU" ("ID_POHYB");
CREATE INDEX "PLATBA_PU_IDX" ON "PLATBA" ("ID_POHYB_UCTU");
